#include <common/ErrorCode.h>

DEFINE_STATIC_ERROR_CODE(SUCCESS,SUCCESS, "ok", "")

DEFINE_STATIC_ERROR_CODE(PARAMS_ERROR,PARAMS_ERROR, "请求参数错误", "")

DEFINE_STATIC_ERROR_CODE(NULL_ERROR,NULL_ERROR, "请求数据为空", "")

DEFINE_STATIC_ERROR_CODE(NO_LOGIN,NO_LOGIN, "未登录", "")

DEFINE_STATIC_ERROR_CODE(NO_AUTH,NO_AUTH, "无权限", "")

DEFINE_STATIC_ERROR_CODE(SYSTEM_ERROR,SYSTEM_ERROR, "系统内部异常", "")